# Задача 1.1

In [2]:
a = 'abcdef'
res = a[::2]+a[1::2]
print(res)

acebdf


# Задача 1.2

In [47]:
a = [1, '1', 123, 'abc']
b = ['1', 2, 0, 42, 35, 'abc']
a = set(a)
b = set(b)
res1 = a.difference(b)
res2 = b.difference(a)
res1.update(res2)
print(res1)

{0, 1, 2, 35, 42, 123}


# Задача 1.3

In [61]:
s = 'A cake is a lie. Miss me? Never gonna give you up, never gonna let you down.'
punct = 0
for i in s:
    if ord(i) < 65 and i != ' ':
        punct += 1
words = len([x for x in s.split()])       
print(words,punct)

17 4


# Задача 2.0

In [2]:
import numpy as np

In [3]:
x = np.array([1, 2, 3, 4, 5])
y = np.array([5, 7, 3, 2, 1])
print(x+y)

[6 9 6 6 6]


# Задача 2.1

In [15]:
A = np.array([[4, 9, 2], [3, 5, 7], [8, 1, 6]])
rows = A.sum(axis = 0) 
columns = A.sum(axis = 1)
if len(set(rows)) == 1:
    print("Cумма элементов строк одинакова")
if len(set(columns)):
     print("Cумма элементов столбцов одинакова")

Cумма элементов строк одинакова
Cумма элементов столбцов одинакова


# Задача 2.2

In [198]:
A = np.random.randint(-100, 100, (10, 10))
A = A.reshape(100)
lst = np.where(A == A.min())
A[lst[::]] = A.max()
A = A.reshape(10,10)
print(A)

[[ 31 -14  26 -54 -90  10 -29  20   4 -72]
 [ 43 -66   8  83 -78  38 -13  -5  32   5]
 [-13 -18 -43  99 -94 -92  98 -16  35  95]
 [-24 -81 -52  32 -78 -93 -65  26 -63 -46]
 [ 71  99  96 -12  92  59 -33  79 -37  -4]
 [-19  51  85  60  19 -43  74  92 -77 -70]
 [ 24  41 -93   9   6  85   3  79 -67 -75]
 [ 92  25 -22   1  83  97  86  46  47  44]
 [ 42  23   0  96 -89 -89 -10 -26  10  78]
 [ 40  -4 -29 -23  68 -30  17 -27 -19 -33]]


# Задача 2.3

In [73]:
a = np.random.randint(0, 2, (10))
b = np.random.randint(0, 2, (10))
print(a)
print(b)
temp = a[np.logical_not(a==b)]
print(1 - temp.size/a.size)

[0 0 0 1 0 0 0 1 1 1]
[0 0 1 0 1 1 1 0 0 1]
0.30000000000000004


# Задача 2.4

In [80]:
n = 10
A = np.random.random((n, n))
i = np.random.randint(0, n, (n))
j = np.random.randint(0, n, (n))
B = A[i[::],j[::]]
print(B)

[ 0.33415855  0.09124024  0.82638117  0.60175336  0.50205464  0.25265325
  0.60746796  0.88058735  0.0677441   0.82899884]


# Задача 2.5

In [84]:
X = np.arange(100)
a = X[:30:]
b = X[30::]

# Задача 2.6

In [104]:
X = np.random.randint(-100, 100, (10)).astype(float)
X = X/X.max()

# Задача 2.7

In [178]:
X = np.random.randint(-100, 100, (10, 10))
lst = X.max(axis = 0)
lst = lst[np.where(lst % 2 == 0)[0]]
print(lst.max())

94


# Задача 2.8

In [180]:
x = np.arange(10)
z = np.ones((9,10))
x + z

array([[  1.,   2.,   3.,   4.,   5.,   6.,   7.,   8.,   9.,  10.],
       [  1.,   2.,   3.,   4.,   5.,   6.,   7.,   8.,   9.,  10.],
       [  1.,   2.,   3.,   4.,   5.,   6.,   7.,   8.,   9.,  10.],
       [  1.,   2.,   3.,   4.,   5.,   6.,   7.,   8.,   9.,  10.],
       [  1.,   2.,   3.,   4.,   5.,   6.,   7.,   8.,   9.,  10.],
       [  1.,   2.,   3.,   4.,   5.,   6.,   7.,   8.,   9.,  10.],
       [  1.,   2.,   3.,   4.,   5.,   6.,   7.,   8.,   9.,  10.],
       [  1.,   2.,   3.,   4.,   5.,   6.,   7.,   8.,   9.,  10.],
       [  1.,   2.,   3.,   4.,   5.,   6.,   7.,   8.,   9.,  10.]])

# Задача 3.1

In [1]:
import pandas as pd

In [58]:
data = pd.read_csv('titanic.csv')

In [59]:
data

PassengerId  Survived  Pclass  \
0              1         0       3   
1              2         1       1   
2              3         1       3   
3              4         1       1   
4              5         0       3   
5              6         0       3   
6              7         0       1   
7              8         0       3   
8              9         1       3   
9             10         1       2   
10            11         1       3   
11            12         1       1   
12            13         0       3   
13            14         0       3   
14            15         0       3   
15            16         1       2   
16            17         0       3   
17            18         1       2   
18            19         0       3   
19            20         1       3   
20            21         0       2   
21            22         1       2   
22            23         1       3   
23            24         1       1   
24            25         0       3   
25            26         1       3   
26            27         0       3   
27            28         0       1   
28            29         1       3   
29            30         0       3   
..           ...       ...     ...   
861          862         0       2   
862          863         1       1   
863          864         0       3   
864          865         0       2   
865          866         1       2   
866          867         1       2   
867          868         0       1   
868          869         0       3   
869          870         1       3   
870          871         0       3   
871          872         1       1   
872          873         0       1   
873          874         0       3   
874          875         1       2   
875          876         1       3   
876          877         0       3   
877          878         0       3   
878          879         0       3   
879          880         1       1   
880          881         1       2   
881          882         0       3   
882          883         0       3   
883          884         0       2   
884          885         0       3   
885          886         0       3   
886          887         0       2   
887          888         1       1   
888          889         0       3   
889          890         1       1   
890          891         0       3   

                                                  Name     Sex   Age  SibSp  \
0                              Braund, Mr. Owen Harris    male  22.0      1   
1    Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                               Heikkinen, Miss. Laina  female  26.0      0   
3         Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                             Allen, Mr. William Henry    male  35.0      0   
5                                     Moran, Mr. James    male   NaN      0   
6                              McCarthy, Mr. Timothy J    male  54.0      0   
7                       Palsson, Master. Gosta Leonard    male   2.0      3   
8    Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)  female  27.0      0   
9                  Nasser, Mrs. Nicholas (Adele Achem)  female  14.0      1   
10                     Sandstrom, Miss. Marguerite Rut  female   4.0      1   
11                            Bonnell, Miss. Elizabeth  female  58.0      0   
12                      Saundercock, Mr. William Henry    male  20.0      0   
13                         Andersson, Mr. Anders Johan    male  39.0      1   
14                Vestrom, Miss. Hulda Amanda Adolfina  female  14.0      0   
15                    Hewlett, Mrs. (Mary D Kingcome)   female  55.0      0   
16                                Rice, Master. Eugene    male   2.0      4   
17                        Williams, Mr. Charles Eugene    male   NaN      0   
18   Vander Planke, Mrs. Julius (Emelia Maria Vande...  female  31.0      1   
19                             Masselmani, Mrs. Fatima  female   NaN

# Задача 3.2

In [66]:
print("Максимальный возраст: ", data['Age'].max())
print("Минимальный возраст: ", data['Age'].min())
avr_age = data['Age'].sum()/(891-177)
print("Средний возраст:", avr_age)

Максимальный возраст:  80.0
Минимальный возраст:  0.42
Средний возраст: 29.69911764705882


# Задача 3.3

In [35]:
surv_cost = data[(data['Survived'] == True) & data['Fare']]

In [38]:
avr_surv_cost= surv_cost['Fare'].sum()/341
print("Средняя цена среди выживших:",avr_surv_cost)

Средняя цена среди выживших: 48.53732961876832


In [41]:
died_cost = data[(data['Survived'] == False) & data['Fare']]
avr_died_cost= died_cost['Fare'].sum()/341
print("Средняя цена среди мертвых:",avr_died_cost)

Средняя цена среди мертвых: 35.60914926686213


# Задача 3.4

In [43]:
data.sort_values(by=['Age'], ascending=False).head(5)

PassengerId  Survived  Pclass                                  Name  \
630          631         1       1  Barkworth, Mr. Algernon Henry Wilson   
851          852         0       3                   Svensson, Mr. Johan   
493          494         0       1               Artagaveytia, Mr. Ramon   
96            97         0       1             Goldschmidt, Mr. George B   
116          117         0       3                  Connors, Mr. Patrick   

      Sex   Age  SibSp  Parch    Ticket     Fare Cabin Embarked  
630  male  80.0      0      0     27042  30.0000   A23        S  
851  male  74.0      0      0    347060   7.7750   NaN        S  
493  male  71.0      0      0  PC 17609  49.5042   NaN        C  
96   male  71.0      0      0  PC 17754  34.6542    A5        C  
116  male  70.5      0      0    370369   7.7500   NaN        Q

# Задача 3.5

In [48]:
data.drop('Cabin', axis=1, inplace=True)
data.head()

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   
3            4         1       1   
4            5         0       3   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female  26.0      0   
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                           Allen, Mr. William Henry    male  35.0      0   

   Parch            Ticket     Fare Embarked  
0      0         A/5 21171   7.2500        S  
1      0          PC 17599  71.2833        C  
2      0  STON/O2. 3101282   7.9250        S  
3      0            113803  53.1000        S  
4      0            373450   8.0500        S

# Задача 3.6

In [68]:
data.set_value(data['Age'].isnull(),'Age',avr_age)


PassengerId  Survived  Pclass  \
0              1         0       3   
1              2         1       1   
2              3         1       3   
3              4         1       1   
4              5         0       3   
5              6         0       3   
6              7         0       1   
7              8         0       3   
8              9         1       3   
9             10         1       2   
10            11         1       3   
11            12         1       1   
12            13         0       3   
13            14         0       3   
14            15         0       3   
15            16         1       2   
16            17         0       3   
17            18         1       2   
18            19         0       3   
19            20         1       3   
20            21         0       2   
21            22         1       2   
22            23         1       3   
23            24         1       1   
24            25         0       3   
25            26         1       3   
26            27         0       3   
27            28         0       1   
28            29         1       3   
29            30         0       3   
..           ...       ...     ...   
861          862         0       2   
862          863         1       1   
863          864         0       3   
864          865         0       2   
865          866         1       2   
866          867         1       2   
867          868         0       1   
868          869         0       3   
869          870         1       3   
870          871         0       3   
871          872         1       1   
872          873         0       1   
873          874         0       3   
874          875         1       2   
875          876         1       3   
876          877         0       3   
877          878         0       3   
878          879         0       3   
879          880         1       1   
880          881         1       2   
881          882         0       3   
882          883         0       3   
883          884         0       2   
884          885         0       3   
885          886         0       3   
886          887         0       2   
887          888         1       1   
888          889         0       3   
889          890         1       1   
890          891         0       3   

                                                  Name     Sex        Age  \
0                              Braund, Mr. Owen Harris    male  22.000000   
1    Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.000000   
2                               Heikkinen, Miss. Laina  female  26.000000   
3         Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.000000   
4                             Allen, Mr. William Henry    male  35.000000   
5                                     Moran, Mr. James    male  29.699118   
6                              McCarthy, Mr. Timothy J    male  54.000000   
7                       Palsson, Master. Gosta Leonard    male   2.000000   
8    Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)  female  27.000000   
9                  Nasser, Mrs. Nicholas (Adele Achem)  female  14.000000   
10                     Sandstrom, Miss. Marguerite Rut  female   4.000000   
11                            Bonnell, Miss. Elizabeth  female  58.000000   
12                      Saundercock, Mr. William Henry    male  20.000000   
13                         Andersson, Mr. Anders Johan    male  39.000000   
14                Vestrom, Miss. Hulda Amanda Adolfina  female  14.000000   
15                    Hewlett, Mrs. (Mary D Kingcome)   female  55.000000   
16                                Rice, Master. Eugene    male   2.000000   
17                        Williams, Mr. Charles Eugene    male  29.699118   
18   Vander Planke, Mrs. Julius (Emelia Maria Vande...  female  31.000000   
19                             Masselmani, Mrs. Fatima  female  29.699118   
20                             

# Задача 3.7

In [69]:
def last_name(fn):
    ln = fn.split(',')[0]
    return ln
last_names = data['Name'].apply(last_name)
last_names    


0               Braund
1              Cumings
2            Heikkinen
3             Futrelle
4                Allen
5                Moran
6             McCarthy
7              Palsson
8              Johnson
9               Nasser
10           Sandstrom
11             Bonnell
12         Saundercock
13           Andersson
14             Vestrom
15             Hewlett
16                Rice
17            Williams
18       Vander Planke
19          Masselmani
20              Fynney
21             Beesley
22             McGowan
23              Sloper
24             Palsson
25             Asplund
26                Emir
27             Fortune
28             O'Dwyer
29            Todoroff
            ...       
861              Giles
862              Swift
863               Sage
864               Gill
865            Bystrom
866       Duran y More
867           Roebling
868      van Melkebeke
869            Johnson
870             Balkic
871           Beckwith
872           Carlsson
873    Vand

In [70]:
data['Last_names'] = last_names

In [71]:
data.head(6)

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   
3            4         1       1   
4            5         0       3   
5            6         0       3   

                                                Name     Sex        Age  \
0                            Braund, Mr. Owen Harris    male  22.000000   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.000000   
2                             Heikkinen, Miss. Laina  female  26.000000   
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.000000   
4                           Allen, Mr. William Henry    male  35.000000   
5                                   Moran, Mr. James    male  29.699118   

   SibSp  Parch            Ticket     Fare Cabin Embarked Last_names  
0      1      0         A/5 21171   7.2500   NaN        S     Braund  
1      1      0          PC 17599  71.2833   C85        C    Cumings  
2      0      0  STON/O2. 3101282   7.9250   NaN        S  Heikkinen  
3      1      0            113803  53.1000  C123        S   Futrelle  
4      0      0            373450   8.0500   NaN        S      Allen  
5      0      0            330877   8.4583   NaN        Q      Moran

In [83]:
groupped = data.groupby("Last_names").count()
groupped

PassengerId  Survived  Pclass  Name  Sex  Age  SibSp  Parch  \
Last_names                                                                      
Abbing                      1         1       1     1    1    1      1      1   
Abbott                      2         2       2     2    2    2      2      2   
Abelson                     2         2       2     2    2    2      2      2   
Adahl                       1         1       1     1    1    1      1      1   
Adams                       1         1       1     1    1    1      1      1   
Ahlin                       1         1       1     1    1    1      1      1   
Aks                         1         1       1     1    1    1      1      1   
Albimona                    1         1       1     1    1    1      1      1   
Alexander                   1         1       1     1    1    1      1      1   
Alhomaki                    1         1       1     1    1    1      1      1   
Ali                         2         2       2     2    2    2      2      2   
Allen                       2         2       2     2    2    2      2      2   
Allison                     3         3       3     3    3    3      3      3   
Allum                       1         1       1     1    1    1      1      1   
Andersen-Jensen             1         1       1     1    1    1      1      1   
Anderson                    1         1       1     1    1    1      1      1   
Andersson                   9         9       9     9    9    9      9      9   
Andreasson                  1         1       1     1    1    1      1      1   
Andrew                      1         1       1     1    1    1      1      1   
Andrews                     2         2       2     2    2    2      2      2   
Angle                       1         1       1     1    1    1      1      1   
Appleton                    1         1       1     1    1    1      1      1   
Arnold-Franchi              2         2       2     2    2    2      2      2   
Artagaveytia                1         1       1     1    1    1      1      1   
Asim                        1         1       1     1    1    1      1      1   
Asplund                     4         4       4     4    4    4      4      4   
Astor                       1         1       1     1    1    1      1      1   
Attalah                     2         2       2     2    2    2      2      2   
Aubart                      1         1       1     1    1    1      1      1   
Augustsson                  1         1       1     1    1    1      1      1   
...                       ...       ...     ...   ...  ...  ...    ...    ...   
Wells                       1         1       1     1    1    1      1      1   
West                        3         3       3     3    3    3      3      3   
Wheadon                     1         1       1     1    1    1      1      1   
White                       2         2       2     2    2    2      2      2   
Wick                        2         2       2     2    2    2      2      2   
Widegren                    1         1       1     1    1    1      1      1   
Widener                     1         1       1     1    1    1      1      1   
Wiklund                     1         1       1     1    1    1      1      1   
Wilhelms                    1         1       1     1    1    1      1      1   
Willey                      1         1       1     1    1    1      1      1   
Williams                    4         4       4     4    4    4      4      4   
Williams-Lambert            1         1       1     1    1    1      1      1   
Windelov                    1         1       1     1    1    1      1      1   
Wiseman                     1         1       1     1    1    1      1      1   
Woolner                     1         1       1     1    1    1      1      1   
Wright                      1         1       1     1    1    1      1      1   
Yasbeck                     2         2       2  

In [92]:
families = groupped[groupped['PassengerId'] > 2]

In [94]:
print("Количество семей: ", len(families.index))

Количество семей:  50
